/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.lucio.pe.cpresentacion;

/**
 *
 * @author Alumno-PB203
 */
public class Contador extends javax.swing.JPanel {

    /**
     * Creates new form Contador
     */
    public Contador() {
        initComponents();
        
   
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TextFieldResultado = new javax.swing.JTextField();
        btnrestar = new javax.swing.JButton();
        btnsumar = new javax.swing.JButton();

        contador.setBackground(new java.awt.Color(102, 255, 204));
        contador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel1.setText("contador");
        contador.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 22, 188, 39));

        TextFieldResultado.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TextFieldResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldResultado.setText("0");
        TextFieldResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldResultadoActionPerformed(evt);
            }
        });
        contador.add(TextFieldResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 326, 121));

        btnrestar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnrestar.setText("restar -1 ");
        btnrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestarActionPerformed(evt);
            }
        });
        contador.add(btnrestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 150, 50));

        btnsumar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnsumar.setText("sumar +1 ");
        btnsumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumarActionPerformed(evt);
            }
        });
        contador.add(btnsumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 150, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contador, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contador, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
         int contadorl = 0;
         
    private void TextFieldResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldResultadoActionPerformed
        
    }//GEN-LAST:event_TextFieldResultadoActionPerformed

    private void btnrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestarActionPerformed
       contadorl--;
       TextFieldResultado.setText(String.valueOf(contadorl));
    }//GEN-LAST:event_btnrestarActionPerformed

    private void btnsumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumarActionPerformed
       contadorl++;
       TextFieldResultado.setText(String.valueOf(contadorl));
    }//GEN-LAST:event_btnsumarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldResultado;
    private javax.swing.JButton btnrestar;
    private javax.swing.JButton btnsumar;
    private javax.swing.JPanel contador;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
